name: GitHub Actions Demo
on: [push]
jobs:
  test-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5
      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - run: |
          python3 -m venv venv |
          . venv/bin/activate |
          pip install -r requirements.txt
      # Step 3: run linter and tests
      - run: |
            . venv/bin/activate |
            flake8 --exclude=venv* --statistics |
            pytest tests/unit -v --cov=calculator
      - name: Deploy package
        run: |
          dbx deploy --files-only
